# Generated by Django 4.1.1 on 2022-12-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('net', models.CharField(max_length=40)),
                ('talk', models.CharField(max_length=40)),
                ('vald', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
